Description: "Create basic notebook instance"
Resources:
  
  BasicNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnCreate:
      - Content:
          Fn::Base64: !Sub |
            #!/bin/bash

            set -e

            sudo -u ec2-user -i <<'EOF'
            cd /home/ec2-user/SageMaker
            git clone https://github.com/aws-samples/jupyter-notebook-for-incident-response
            EOF
      OnStart:
      - Content:
          Fn::Base64: !Sub |
            #!/bin/bash

            set -e

            # OVERVIEW
            # This script gets value from Notebook Instance's tag and sets it as environment
            # variable for all process including Jupyter in SageMaker Notebook Instance
            #
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -qq awscliv2.zip
            sudo ./aws/install --update
            rm -rf aws
            rm awscliv2.zip

            rm -f /home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/aws

            

            sudo -u ec2-user -i <<'EOF'

            ENVIRONMENT=python3
            source /home/ec2-user/anaconda3/bin/activate "$ENVIRONMENT"
            rm  /home/ec2-user/anaconda3/envs/python3/bin/aws
            pip install --upgrade "$PACKAGE"
            pip install -e /home/ec2-user/SageMaker/jupyter-notebook-for-incident-response/runbooks
            source /home/ec2-user/anaconda3/bin/deactivate


            EOF

            echo "Restarting the Jupyter server.."
            sudo systemctl restart jupyter-server

  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName:  !Sub '${AWS::StackName}-notebook-instance' 
      InstanceType: "ml.t2.medium"
      RoleArn: !GetAtt ExecutionRole.Arn
      LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
      
  ExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName:  !Sub '${AWS::StackName}-notebook-role'
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "sagemaker.amazonaws.com"
          Action: 
          - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "sagemaker-notebook-policy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: 'arn:aws:s3:::*/*'
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                Resource: 'arn:aws:s3:::*'
              - Effect: "Allow"
                Action:                 
                  - "athena:CreateNamedQuery"
                  - "athena:GetQueryExecution"
                  - "athena:GetQueryResults"
                  - "athena:StartQueryExecution"
                Resource: !Sub 'arn:aws:athena:*:${AWS::AccountId}:workgroup/*'
              - Effect: "Allow"
                Action:
                  - "glue:CreateDatabase"
                  - "glue:CreateTable"
                  - "glue:GetDatabase"
                  - "glue:GetTable"
                Resource: [ !Sub 'arn:aws:glue:*:${AWS::AccountId}:database/*',
                            !Sub 'arn:aws:glue:*:${AWS::AccountId}:catalog',
                          !Sub 'arn:aws:glue:*:${AWS::AccountId}:table/*/*'
                          ]
              - Effect: "Allow"
                Action:
                  - "iam:PutUserPolicy"
                  - "iam:UpdateAccessKey"
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:user/*'                
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance
    Value: !GetAtt BasicNotebookInstance.NotebookInstanceName